version: '2'

volumes:
  foncier_extracts:
  foncier_staticfiles:
  ldap_data:
  ldap_config:
  redis_data:
  foncier_pg_data:


services:
  # Flask Main Application
  app:
    build: .
    image: georchestra/foncier-app:19.04
    ports:
      # debug:
      - "5000:5000"
    environment:
      - UWSGI_ENABLE_THREADS=1
      - UWSGI_SINGLE_INTERPRETER=1
      - UWSGI_PROCESSES=3
      - UWSGI_THREADS=2
      - UWSGI_MASTER=1
      - UWSGI_SOCKET_TIMEOUT=2400
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - LDAP_URI=ldap://ldap:389
      - LDAP_BINDDN=cn=admin,dc=georchestra,dc=org
      - LDAP_PASSWD=secret
      - LDAP_ORGS_BASEDN=ou=orgs,dc=georchestra,dc=org
      - LDAP_SEARCH_FILTER=(&(cn=%s)(objectClass=groupOfMembers))
      - FONCIER_EXTRACTS_DIR=/extracts
      - DEBUG=False
    volumes:
      - foncier_extracts:/extracts:ro


  # Worker
  worker:
    build: celery
    image: georchestra/foncier-worker:19.04
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - PG_CONNECT_STRING=host=database port=5432 user=geoserver dbname=geoserver password=geoserver
      - LOCAL_SMTP_HOST=smtp
      - PROCESS_TIMEOUT=7200
      - FONCIER_EXTRACTS_RETENTION_DAYS=1
      - FONCIER_EXTRACTS_DIR=/extracts
    volumes:
      - foncier_staticfiles:/static:ro
      - foncier_extracts:/extracts


  # Proxy
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./resources/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app


  # sample geOrchestra LDAP
  ldap:
    image: georchestra/ldap:19.04
    environment:
      - SLAPD_ORGANISATION=georchestra
      - SLAPD_DOMAIN=georchestra.org
      - SLAPD_PASSWORD=secret
      - SLAPD_ADDITIONAL_MODULES=groupofmembers
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap
    ports:
      - "3899:389"


  # Message broker
  redis:
    image: redis:5.0
    volumes:
      - redis_data:/data


  # Database with Foncier (geo)data
  database:
    image: camptocamp/postgres:9.6
    volumes:
      - foncier_pg_data:/var/lib/postgresql/data
      - ./resources/db/sql:/docker-entrypoint-initdb.d/
    ports:
      - "54322:5432"
    environment:
      POSTGRES_DB: geoserver
      POSTGRES_PASSWORD: geoserver
      POSTGRES_USER: geoserver


  # SMTP
  smtp:
    image: camptocamp/smtp-sink

  webmail:
    image: camptocamp/roundcube
    ports:
      - "8081:80"
    volumes_from:
      - smtp:rw
    environment:
      - IMAP_HOSTNAME=courier-imap
      - SMTP_HOSTNAME=smtp

  courier-imap:
    image: camptocamp/courier-imap
    ports:
      - "143:143"
    volumes_from:
      - smtp:rw
